doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from Inno\Migrations
        # as migrations classes should NOT be autoloaded
        'AppMigrations': '%kernel.project_dir%/src/Migrations'
    enable_profiler: false
