# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
# Bundle sizing: https://symfony.com/bundles/LiipImagineBundle/current/filters/sizing.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:

        # name our filter set "my_thumb_filter"
        user_thumb:
            filters:

                # use and setup the "thumbnail" filter
                thumbnail:

                    # set the thumbnail size to "32x32" pixels
                    size: [100, 100]

                    # crop the input image, if required
                    mode: outbound
        
        user_profile:
            filters:

                # use and setup the "thumbnail" filter
                thumbnail:

                    # set the thumbnail size to "32x32" pixels
                    size: [200, 200]

                    # crop the input image, if required
                    mode: outbound            
                    
        user_preview:
            filters:

                # use and setup the "thumbnail" filter
                thumbnail:

                    # set the thumbnail size to "32x32" pixels
                    size: [250, 250]

                    # crop the input image, if required
                    mode: outbound          
        
        user_crop_filter:
            filters:

                # use and setup the "crop" filter
                crop:

                    # set the size of the cropping area
                    size: [ 200, 200 ]

                    # set the starting coordinates of the crop
                    start: [ 0, 0 ]            
