# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
# Bundle sizing: https://symfony.com/bundles/LiipImagineBundle/current/filters/sizing.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        # name our filter set "my_thumb_filter"
        user_thumb:
            filters:
                thumbnail:
                    size: [100, 100]
                    mode: outbound
        
        user_profile:
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
        user_preview:
            filters:
                thumbnail:
                    size: [250, 250]
                    mode: outbound
        entry_preview:
            filters:
                thumbnail:
                    size: [ 380, 200 ]
                    mode: outbound
        entry_view:
            filters:
                thumbnail:
                    size: [ 1100, 400 ]
                    mode: outbound
        user_crop_filter:
            filters:
                crop:
                    # set the size of the cropping area
                    size: [ 200, 200 ]
                    # set the starting coordinates of the crop
                    start: [ 0, 0 ]            
