twig:
    default_path: '%kernel.project_dir%/templates/theme/default'
#    form_themes:
#            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        datetime_format: '%app.datetime_format%'
        date_format: '%app.date_format%'
        # bootstrap class, can be 'container' or 'container-fluid'
        container: 'container'
when@test:
    twig:
        strict_variables: true
