twig:
    path:
        '%kernel.project_dir%/templates/theme/%app.theme%'
    globals:
        datetime_format: '%app.datetime_format%'
        date_format: '%app.date_format%'
        shop: '@App\Service\MarketPlace\Store\Order\ShopService'
        messages: '@App\Service\MessageCounter'
when@test:
    twig:
        strict_variables: true
