twig:
    path:
        '%kernel.project_dir%/templates/theme/%app.theme%'
    globals:
        datetime_format: '%app.datetime_format%'
        date_format: '%app.date_format%'
        time_format: '%app.time_format%'
        shop: '@Inno\Service\MarketPlace\Store\Order\ShopService'
        msg: '@Inno\Service\MessageCounter'
when@test:
    twig:
        strict_variables: true
