twig:
    default_path: '%kernel.project_dir%/templates/theme/%theme%'
    globals:
        datetime_format: '%app.datetime_format%'
        date_format: '%app.date_format%'
        # bootstrap class, can be 'container' or 'container-fluid'
        container: 'container'
when@test:
    twig:
        strict_variables: true
