<?php

declare(strict_types=1);

namespace AppMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250115163149 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE file_manager (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, file_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A1429C8293CB796C ON file_manager (file_id)');
        $this->addSql('CREATE INDEX IDX_A1429C827E3C61F9 ON file_manager (owner_id)');
        $this->addSql('ALTER TABLE file_manager ADD CONSTRAINT FK_A1429C8293CB796C FOREIGN KEY (file_id) REFERENCES attach (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE file_manager ADD CONSTRAINT FK_A1429C827E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE file_manager DROP CONSTRAINT FK_A1429C8293CB796C');
        $this->addSql('ALTER TABLE file_manager DROP CONSTRAINT FK_A1429C827E3C61F9');
        $this->addSql('DROP TABLE file_manager');
    }
}
