<?php

declare(strict_types=1);

namespace AppMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250123173426 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE taggable (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, taggable_id BIGINT NOT NULL, type VARCHAR(255) NOT NULL, tag_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6243ADB9BAD26311 ON taggable (tag_id)');
        $this->addSql('CREATE INDEX idx_taggable_id ON taggable (taggable_id)');
        $this->addSql('CREATE INDEX idx_type ON taggable (type)');
        $this->addSql('ALTER TABLE taggable ADD CONSTRAINT FK_6243ADB9BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE taggable DROP CONSTRAINT FK_6243ADB9BAD26311');
        $this->addSql('DROP TABLE taggable');
    }
}
